# Generated by Django 2.2 on 2021-07-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default='2021-07-08')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TotalVisitNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=30)),
                ('end_point', models.CharField(default='/', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(default='2021-07-08')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
